export interface UserInterface {
   login: string;
   avatar_url: string;
   email?: string | undefined;
}

// [
//    "avatar_url",
//    "events_url",
//    "followers_url",
//    "following_url",
//    "gists_url",
//    "gravatar_id",
//    "html_url",
//    "id",
//    "node_id",
//    "login",
//    "organizations_url",
//    "received_events_url",
//    "repos_url",
//    "site_admin",
//    "starred_url",
//    "subscriptions_url",
//    "type",
//    "url",
//    "bio",
//    "blog",
//    "company",
//    "email",
//    "followers",
//    "following",
//    "hireable",
//    "location",
//    "name",
//    "public_gists",
//    "public_repos",
//    "created_at",
//    "updated_at",
//    "collaborators",
//    "disk_usage",
//    "owned_private_repos",
//    "private_gists",
//    "total_private_repos",
//    "two_factor_authentication",
// ];
