import { Author, Task } from "@/types/interfaces";

export const author: Author = {
   avatar_url: "https://avatars.githubusercontent.com/u/131165484?v=4",
   events_url: "https://api.github.com/users/websolutionsharare/events%7B/privacy%7D",
   followers_url: "https://api.github.com/users/websolutionsharare/followers",
   following_url: "https://api.github.com/users/websolutionsharare/following%7B/other_user%7D",
   gists_url: "https://api.github.com/users/websolutionsharare/gists%7B/gist_id%7D",
   gravatar_id: "",
   html_url: "https://github.com/websolutionsharare",
   id: "131165484",
   login: "websolutionsharare",
   node_id: "U_kgDOB9FtLA",
   organizations_url: "https://api.github.com/users/websolutionsharare/orgs",
   patch_url: undefined,
   received_events_url: "https://api.github.com/users/websolutionsharare/received_events",
   repos_url: "https://api.github.com/users/websolutionsharare/repos",
   site_admin: false,
   starred_url: "https://api.github.com/users/websolutionsharare/starred%7B/owner%7D%7B/repo%7D",
   subscriptions_url: "https://api.github.com/users/websolutionsharare/subscriptions",
   type: "User",
   url: "https://api.github.com/users/websolutionsharare",
};

export const sampleTasks: Task[] = [
   {
      priority: "normal",
      inner_issue: {
         id: 1,
         node_id: "MDU6SXNzdWUx",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/1/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/1/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/1/events",
         html_url: "https://github.com/octocat/Hello-World/issues/1",
         number: 1,
         state: "open",
         state_reason: undefined,
         title: "Found a bug in the login page",
         body: "When trying to login with invalid credentials, the page crashes instead of showing an error message.",
         body_text:
            "When trying to login with invalid credentials, the page crashes instead of showing an error message.",
         body_html:
            "<p>When trying to login with invalid credentials, the page crashes instead of showing an error message.</p>",
         user: author,
         labels: ["bug", "high priority"],
         assignee: author,
         assignees: [author],
         author_association: "CONTRIBUTOR",
         milestone: "Sprint 15",
         locked: false,
         active_lock_reason: undefined,
         comments: 3,
         pull_request: undefined,
         closed_at: "",
         closed_by: author,
         created_at: "2023-01-15T10:00:00Z",
         updated_at: "2023-01-16T14:30:00Z",
      },
   },
   {
      priority: "low",
      inner_issue: {
         id: 2,
         node_id: "MDU6SXNzdWUy",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/2",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/2/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/2/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/2/events",
         html_url: "https://github.com/octocat/Hello-World/issues/2",
         number: 2,
         state: "closed",
         state_reason: "completed",
         title: "Add dark mode support",
         body: "Users have requested a dark mode option for the application.",
         body_text: "Users have requested a dark mode option for the application.",
         body_html: "<p>Users have requested a dark mode option for the application.</p>",
         user: author,
         labels: ["enhancement", "UI"],
         assignee: author,
         assignees: [author],
         author_association: "MEMBER",
         milestone: "Sprint 14",
         locked: false,
         active_lock_reason: undefined,
         comments: 5,
         pull_request: "https://api.github.com/repos/octocat/Hello-World/pulls/42",
         closed_at: "2023-01-10T16:20:00Z",
         closed_by: author,
         created_at: "2022-12-20T09:15:00Z",
         updated_at: "2023-01-10T16:20:00Z",
      },
   },
   {
      priority: "high",
      inner_issue: {
         id: 3,
         node_id: "MDU6SXNzdWUz",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/3",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/3/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/3/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/3/events",
         html_url: "https://github.com/octocat/Hello-World/issues/3",
         number: 3,
         state: "open",
         state_reason: undefined,
         title: "Documentation missing for API endpoint /users",
         body: "The /users endpoint needs proper documentation in our API docs.",
         body_text: "The /users endpoint needs proper documentation in our API docs.",
         body_html: "<p>The /users endpoint needs proper documentation in our API docs.</p>",
         user: author,
         labels: ["documentation"],
         assignee: author,
         assignees: [author],
         author_association: "COLLABORATOR",
         milestone: undefined,
         locked: false,
         active_lock_reason: undefined,
         comments: 1,
         pull_request: undefined,
         closed_at: "",
         closed_by: author,
         created_at: "2023-01-18T11:30:00Z",
         updated_at: "2023-01-18T11:30:00Z",
      },
   },
   {
      priority: "urgent",
      inner_issue: {
         id: 4,
         node_id: "MDU6SXNzdWU0",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/4",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/4/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/4/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/4/events",
         html_url: "https://github.com/octocat/Hello-World/issues/4",
         number: 4,
         state: "open",
         state_reason: undefined,
         title: "Performance issue with large datasets",
         body: "When loading more than 1000 items, the UI becomes unresponsive.",
         body_text: "When loading more than 1000 items, the UI becomes unresponsive.",
         body_html: "<p>When loading more than 1000 items, the UI becomes unresponsive.</p>",
         user: author,
         labels: ["performance", "needs-investigation"],
         assignee: author,
         assignees: [author],
         author_association: "CONTRIBUTOR",
         milestone: "Sprint 16",
         locked: false,
         active_lock_reason: undefined,
         comments: 7,
         pull_request: undefined,
         closed_at: "",
         closed_by: author,
         created_at: "2023-01-17T14:45:00Z",
         updated_at: "2023-01-19T09:10:00Z",
      },
   },
   {
      priority: "normal",
      inner_issue: {
         id: 5,
         node_id: "MDU6SXNzdWU1",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/5",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/5/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/5/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/5/events",
         html_url: "https://github.com/octocat/Hello-World/issues/5",
         number: 5,
         state: "closed",
         state_reason: "not_planned",
         title: "Support for Internet Explorer",
         body: "Should we continue supporting IE11?",
         body_text: "Should we continue supporting IE11?",
         body_html: "<p>Should we continue supporting IE11?</p>",
         user: author,
         labels: ["browser-support", "discussion"],
         assignee: author,
         assignees: [author],
         author_association: "MEMBER",
         milestone: undefined,
         locked: true,
         active_lock_reason: "too heated",
         comments: 42,
         pull_request: undefined,
         closed_at: "2023-01-12T18:00:00Z",
         closed_by: author,
         created_at: "2022-12-01T10:00:00Z",
         updated_at: "2023-01-12T18:00:00Z",
      },
   },
   {
      priority: "normal",
      inner_issue: {
         id: 6,
         node_id: "MDU6SXNzdWU2",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/6",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/6/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/6/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/6/events",
         html_url: "https://github.com/octocat/Hello-World/issues/6",
         number: 6,
         state: "open",
         state_reason: undefined,
         title: "Mobile view layout broken on small screens",
         body: "The dashboard layout breaks on screens smaller than 320px wide.",
         body_text: "The dashboard layout breaks on screens smaller than 320px wide.",
         body_html: "<p>The dashboard layout breaks on screens smaller than 320px wide.</p>",
         user: author,
         labels: ["bug", "mobile"],
         assignee: author,
         assignees: [author],
         author_association: "CONTRIBUTOR",
         milestone: "Sprint 15",
         locked: false,
         active_lock_reason: undefined,
         comments: 2,
         pull_request: undefined,
         closed_at: "",
         closed_by: author,
         created_at: "2023-01-16T13:20:00Z",
         updated_at: "2023-01-17T08:45:00Z",
      },
   },
   {
      priority: "normal",
      inner_issue: {
         id: 7,
         node_id: "MDU6SXNzdWU3",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/7",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/7/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/7/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/7/events",
         html_url: "https://github.com/octocat/Hello-World/issues/7",
         number: 7,
         state: "open",
         state_reason: undefined,
         title: "Implement user profile editing functionality",
         body: "Users should be able to edit their profile information.",
         body_text: "Users should be able to edit their profile information.",
         body_html: "<p>Users should be able to edit their profile information.</p>",
         user: author,
         labels: ["feature", "backend"],
         assignee: author,
         assignees: [author],
         author_association: "MEMBER",
         milestone: "Q1 Roadmap",
         locked: false,
         active_lock_reason: undefined,
         comments: 0,
         pull_request: undefined,
         closed_at: "",
         closed_by: author,
         created_at: "2023-01-20T09:00:00Z",
         updated_at: "2023-01-20T09:00:00Z",
      },
   },
   {
      priority: "normal",
      inner_issue: {
         id: 8,
         node_id: "MDU6SXNzdWU4",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/8",
         repository_url: "https://api.github.com/repos/octocat/Hello-World",
         labels_url: "https://api.github.com/repos/octocat/Hello-World/issues/8/labels",
         comments_url: "https://api.github.com/repos/octocat/Hello-World/issues/8/comments",
         events_url: "https://api.github.com/repos/octocat/Hello-World/issues/8/events",
         html_url: "https://github.com/octocat/Hello-World/issues/8",
         number: 8,
         state: "closed",
         state_reason: "completed",
         title: "Update dependencies to latest versions",
         body: "Several dependencies have security updates available.",
         body_text: "Several dependencies have security updates available.",
         body_html: "<p>Several dependencies have security updates available.</p>",
         user: author,
         labels: ["dependencies", "security"],
         assignee: author,
         assignees: [author],
         author_association: "MEMBER",
         milestone: "Maintenance",
         locked: false,
         active_lock_reason: undefined,
         comments: 1,
         pull_request: "https://api.github.com/repos/octocat/Hello-World/pulls/56",
         closed_at: "2023-01-14T12:30:00Z",
         closed_by: author,
         created_at: "2023-01-10T08:00:00Z",
         updated_at: "2023-01-14T12:30:00Z",
      },
   },
];
