import { Author, Task } from "@/types/interfaces";

export const author: Author = {
   avatar_url: "https://avatars.githubusercontent.com/u/131165484?v=4",
   events_url: "https://api.github.com/users/websolutionsharare/events%7B/privacy%7D",
   followers_url: "https://api.github.com/users/websolutionsharare/followers",
   following_url: "https://api.github.com/users/websolutionsharare/following%7B/other_user%7D",
   gists_url: "https://api.github.com/users/websolutionsharare/gists%7B/gist_id%7D",
   gravatar_id: "",
   html_url: "https://github.com/websolutionsharare",
   id: "131165484",
   login: "websolutionsharare",
   node_id: "U_kgDOB9FtLA",
   organizations_url: "https://api.github.com/users/websolutionsharare/orgs",
   patch_url: undefined,
   received_events_url: "https://api.github.com/users/websolutionsharare/received_events",
   repos_url: "https://api.github.com/users/websolutionsharare/repos",
   site_admin: false,
   starred_url: "https://api.github.com/users/websolutionsharare/starred%7B/owner%7D%7B/repo%7D",
   subscriptions_url: "https://api.github.com/users/websolutionsharare/subscriptions",
   type: "User",
   url: "https://api.github.com/users/websolutionsharare",
};

export const sampleTasks: Task[] = [
   {
      priority: "normal",
      innerIssue: {
         id: 1,
         nodeId: "MDU6SXNzdWUx",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/1/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/1/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/1/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/1",
         number: 1,
         state: "open",
         stateReason: undefined,
         title: "Found a bug in the login page",
         body: "When trying to login with invalid credentials, the page crashes instead of showing an error message.",
         bodyText:
            "When trying to login with invalid credentials, the page crashes instead of showing an error message.",
         bodyHtml:
            "<p>When trying to login with invalid credentials, the page crashes instead of showing an error message.</p>",
         user: author,
         labels: ["bug", "high priority"],
         assignee: author,
         assignees: [author],
         authorAssociation: "CONTRIBUTOR",
         milestone: "Sprint 15",
         locked: false,
         activeLockReason: undefined,
         comments: 3,
         pullRequest: undefined,
         closedAt: "",
         closedBy: author,
         createdAt: "2023-01-15T10:00:00Z",
         updatedAt: "2023-01-16T14:30:00Z",
      },
   },
   {
      priority: "low",
      innerIssue: {
         id: 2,
         nodeId: "MDU6SXNzdWUy",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/2",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/2/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/2/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/2/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/2",
         number: 2,
         state: "closed",
         stateReason: "completed",
         title: "Add dark mode support",
         body: "Users have requested a dark mode option for the application.",
         bodyText: "Users have requested a dark mode option for the application.",
         bodyHtml: "<p>Users have requested a dark mode option for the application.</p>",
         user: author,
         labels: ["enhancement", "UI"],
         assignee: author,
         assignees: [author],
         authorAssociation: "MEMBER",
         milestone: "Sprint 14",
         locked: false,
         activeLockReason: undefined,
         comments: 5,
         pullRequest: "https://api.github.com/repos/octocat/Hello-World/pulls/42",
         closedAt: "2023-01-10T16:20:00Z",
         closedBy: author,
         createdAt: "2022-12-20T09:15:00Z",
         updatedAt: "2023-01-10T16:20:00Z",
      },
   },
   {
      priority: "high",
      innerIssue: {
         id: 3,
         nodeId: "MDU6SXNzdWUz",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/3",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/3/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/3/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/3/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/3",
         number: 3,
         state: "open",
         stateReason: undefined,
         title: "Documentation missing for API endpoint /users",
         body: "The /users endpoint needs proper documentation in our API docs.",
         bodyText: "The /users endpoint needs proper documentation in our API docs.",
         bodyHtml: "<p>The /users endpoint needs proper documentation in our API docs.</p>",
         user: author,
         labels: ["documentation"],
         assignee: author,
         assignees: [author],
         authorAssociation: "COLLABORATOR",
         milestone: undefined,
         locked: false,
         activeLockReason: undefined,
         comments: 1,
         pullRequest: undefined,
         closedAt: "",
         closedBy: author,
         createdAt: "2023-01-18T11:30:00Z",
         updatedAt: "2023-01-18T11:30:00Z",
      },
   },
   {
      priority: "urgent",
      innerIssue: {
         id: 4,
         nodeId: "MDU6SXNzdWU0",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/4",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/4/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/4/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/4/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/4",
         number: 4,
         state: "open",
         stateReason: undefined,
         title: "Performance issue with large datasets",
         body: "When loading more than 1000 items, the UI becomes unresponsive.",
         bodyText: "When loading more than 1000 items, the UI becomes unresponsive.",
         bodyHtml: "<p>When loading more than 1000 items, the UI becomes unresponsive.</p>",
         user: author,
         labels: ["performance", "needs-investigation"],
         assignee: author,
         assignees: [author],
         authorAssociation: "CONTRIBUTOR",
         milestone: "Sprint 16",
         locked: false,
         activeLockReason: undefined,
         comments: 7,
         pullRequest: undefined,
         closedAt: "",
         closedBy: author,
         createdAt: "2023-01-17T14:45:00Z",
         updatedAt: "2023-01-19T09:10:00Z",
      },
   },
   {
      priority: "normal",
      innerIssue: {
         id: 5,
         nodeId: "MDU6SXNzdWU1",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/5",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/5/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/5/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/5/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/5",
         number: 5,
         state: "closed",
         stateReason: "not_planned",
         title: "Support for Internet Explorer",
         body: "Should we continue supporting IE11?",
         bodyText: "Should we continue supporting IE11?",
         bodyHtml: "<p>Should we continue supporting IE11?</p>",
         user: author,
         labels: ["browser-support", "discussion"],
         assignee: author,
         assignees: [author],
         authorAssociation: "MEMBER",
         milestone: undefined,
         locked: true,
         activeLockReason: "too heated",
         comments: 42,
         pullRequest: undefined,
         closedAt: "2023-01-12T18:00:00Z",
         closedBy: author,
         createdAt: "2022-12-01T10:00:00Z",
         updatedAt: "2023-01-12T18:00:00Z",
      },
   },
   {
      priority: "normal",
      innerIssue: {
         id: 6,
         nodeId: "MDU6SXNzdWU2",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/6",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/6/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/6/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/6/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/6",
         number: 6,
         state: "open",
         stateReason: undefined,
         title: "Mobile view layout broken on small screens",
         body: "The dashboard layout breaks on screens smaller than 320px wide.",
         bodyText: "The dashboard layout breaks on screens smaller than 320px wide.",
         bodyHtml: "<p>The dashboard layout breaks on screens smaller than 320px wide.</p>",
         user: author,
         labels: ["bug", "mobile"],
         assignee: author,
         assignees: [author],
         authorAssociation: "CONTRIBUTOR",
         milestone: "Sprint 15",
         locked: false,
         activeLockReason: undefined,
         comments: 2,
         pullRequest: undefined,
         closedAt: "",
         closedBy: author,
         createdAt: "2023-01-16T13:20:00Z",
         updatedAt: "2023-01-17T08:45:00Z",
      },
   },
   {
      priority: "normal",
      innerIssue: {
         id: 7,
         nodeId: "MDU6SXNzdWU3",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/7",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/7/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/7/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/7/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/7",
         number: 7,
         state: "open",
         stateReason: undefined,
         title: "Implement user profile editing functionality",
         body: "Users should be able to edit their profile information.",
         bodyText: "Users should be able to edit their profile information.",
         bodyHtml: "<p>Users should be able to edit their profile information.</p>",
         user: author,
         labels: ["feature", "backend"],
         assignee: author,
         assignees: [author],
         authorAssociation: "MEMBER",
         milestone: "Q1 Roadmap",
         locked: false,
         activeLockReason: undefined,
         comments: 0,
         pullRequest: undefined,
         closedAt: "",
         closedBy: author,
         createdAt: "2023-01-20T09:00:00Z",
         updatedAt: "2023-01-20T09:00:00Z",
      },
   },
   {
      priority: "normal",
      innerIssue: {
         id: 8,
         nodeId: "MDU6SXNzdWU4",
         url: "https://api.github.com/repos/octocat/Hello-World/issues/8",
         repositoryUrl: "https://api.github.com/repos/octocat/Hello-World",
         labelsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/8/labels",
         commentsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/8/comments",
         eventsUrl: "https://api.github.com/repos/octocat/Hello-World/issues/8/events",
         htmlUrl: "https://github.com/octocat/Hello-World/issues/8",
         number: 8,
         state: "closed",
         stateReason: "completed",
         title: "Update dependencies to latest versions",
         body: "Several dependencies have security updates available.",
         bodyText: "Several dependencies have security updates available.",
         bodyHtml: "<p>Several dependencies have security updates available.</p>",
         user: author,
         labels: ["dependencies", "security"],
         assignee: author,
         assignees: [author],
         authorAssociation: "MEMBER",
         milestone: "Maintenance",
         locked: false,
         activeLockReason: undefined,
         comments: 1,
         pullRequest: "https://api.github.com/repos/octocat/Hello-World/pulls/56",
         closedAt: "2023-01-14T12:30:00Z",
         closedBy: author,
         createdAt: "2023-01-10T08:00:00Z",
         updatedAt: "2023-01-14T12:30:00Z",
      },
   },
];
