// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "UnknownError": AppErrorContext };

export type AppErrorContext = { message: string, 
/**
 * fully qualified name of the function raising the error
 * # Example
 * ```
 * "crate::utils::get_store"
 * ```
 */
origin: string, };
