name: "Test Build"

on:
   push:
      branches:
         - testing
env:
   CLIENT_ID: ${{ secrets.CLIENT_ID }}
   CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
   PROCEED_TO_AUTH_URI: ${{ secrets.PROCEED_TO_AUTH_URI }}
   FINNISH_AUTH_URI: ${{ secrets.FINNISH_AUTH_URI }}

jobs:
   test-tauri:
      strategy:
         fail-fast: false
         matrix:
            include:
               - platform: "macos-latest"
                 args: "--target aarch64-apple-darwin"
               - platform: "macos-latest"
                 args: "--target x86_64-apple-darwin"
               - platform: "ubuntu-22.04"
                 args: ""
               - platform: "windows-latest"
                 args: ""

      runs-on: ${{ matrix.platform }}
      defaults:
         run:
            shell: "bash"
      steps:
         - uses: actions/checkout@v4

         - name: install dependencies (ubuntu only)
           if: matrix.platform == 'ubuntu-22.04'
           run: |
              sudo apt-get update
              sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

         - name: install Rust stable
           uses: dtolnay/rust-toolchain@stable
           with:
              targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: latest

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: lts/*
              cache: "pnpm"

         - name: install frontend dependencies
           run: pnpm install

         - name: Cache Rust build
           uses: swatinem/rust-cache@v2
           with:
              workspaces: "./src-tauri -> target"

         - name: Create .env file for Vite
           run: |
              echo VITE_CLIENT_ID=${{secrets.CLIENT_ID }} >> .env
              echo VITE_CLIENT_SECRET=${{secrets.CLIENT_SECRET }} >> .env
              echo VITE_PROCEED_TO_AUTH_URI=${{secrets.PROCEED_TO_AUTH_URI }} >> .env
              echo VITE_FINNISH_AUTH_URI=${{secrets.FINNISH_AUTH_URI }} >> .env

         - name: Create .env file for Tauri
           run: |
              echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> ./src-tauri/.env
              echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> ./src-tauri/.env

         # If tagName and releaseId are omitted tauri-action will only build the app and won't try to upload any assets.
         - uses: tauri-apps/tauri-action@v0
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              args: ${{ matrix.args }}
